### ISSUE TITLE
Exception occurred when generating a document

### ISSUE THREAD

**Issue by MarkKleinHaneveldNRC** [Nasdanika/cli#1]
I encounter this error message when trying to generate a document:

![screenshot](https://github.com/user-attachments/assets/49240df7-c9a9-486c-9499-54f28236c801)

**Comment by pvlasov** [comment]
Hello,

This issue was fixed in 2024.10.0. 

If you are using GitHub Actions, please upgrade ``.github/workflows/site.yml`` to 2024.10.0 at lines 33 and 35 as shown below:

* Line 33: ``        run: wget https://github.com/Nasdanika/cli/releases/download/maven-2024.10.0/nsd-cli.zip``
* Line 35: ``        run: unzip nsd-cli.zip``
 
Otherwise, download the new distribution from https://github.com/Nasdanika/cli/releases/tag/maven-2024.10.0. If run into issues, I'd recommend building it locally - ``mvn verify``. Sometimes there is a problem with adding modules - the module list may differ between JVM vendors. It will be fixed in the new release. 

Shall you still face issues - let me know by reopening this issue!
